fix(config): use convenient jest config + upgrade Jest@28
Facing those errors:
ReferenceError: TextEncoder is not defined

We need to use custom-test-env with jest-environment-jsdom
as jest-environment-jsdom came in version 28, and needs to get
the same version as Jest, Jest got upgraded.